### PR TITLE
Initial commit for CocoaPod support

### LINKED ISSUE #9: Add CocoaPods Support
Like the title says :smile:

### PR DESCRIPTION
**Pull request by davidrothera**
Managed to get CocoaPod support in without changing the layout of the project which makes things nice and easy :wink: 

In order to push this to CocoaPods once merged there are just a few last steps which you need to do as the owner/maintainer:

* Create Pod trunk account [here](https://guides.cocoapods.org/making/getting-setup-with-trunk)
* `pod trunk push NAME.podspec`

To update in future just update the version number and tag name in the podspec and push to trunk :+1: 

Fixes #9

### CODE REVIEW

**Comment by skreutzberger** [comment]
Awesome, thank you so much! I will signup there now and do the setup asks and come back if I hit a wall or if I have something to test :+1:

**Comment by skreutzberger** [comment]
Very odd ... 

I have registered, I can do `pod trunk me`and `pod lib lint` and all looks good but somehow the initial push does not work? I even bumped the version to v0.2.2 so that all is new. Do you have any idea what I am doing wrong?

cocoapods

**Comment by davidrothera** [comment]
I'll take a look shortly, just out for food :smile:

**Comment by davidrothera** [comment]
Try --verbose on the push and see if it says why it's failing

**Comment by skreutzberger** [comment]
thanks for the hint. The issue was that I had not pushed the new tag to Github. Now the `pod trunk push` call worked.

Did it work? I checked cocoapods.org but there is just version 0.2.1 and it looks odd. It does not have a document page or so. Is it still already working? And if yes what should I add to Readme?

Gosh, I am such a Cocoapods Newbie :(

cocoapods2

**Comment by davidrothera** [comment]
The indexing on cocoa pods site lags a little but it's showing 0.2.2 now :smiley:

**Pull request merged**
