### PR TITLE
Make usable in extensions

### PR DESCRIPTION
**Pull request by r-peck**

### CODE REVIEW

**Comment by skreutzberger** [comment]
I am not an expert on Xcode building. Can you please explain the purpose of the PR, what it fixes and what possible side-effects it would create? Thanks!

**Comment by r-peck** [comment]
Sure, Apple limits access to some APIs in application extensions. When linking against a framework in an extension, Xcode expects the framework to be flagged as not using those APIs. This flags the resulting framework and should prevent access to those APIs when building the framework.

The restricted APIs are mostly related to running in an application environment (as opposed to an extension - the sharedApplication singleton, long running background tasks, not including upload/download with NSURLSession) and access to external resources (camera, microphone, AirDrop). As long as those APIs are not being used, it should not impact this framework. More information can be found here: https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6

**Comment by skreutzberger** [comment]
So if I understand it correctly then your flag is limiting SwiftyBeaver’s capability to optionally upload a file to a logging server or to do other background tasks? What are the benefits for the end user and developer? 

I just fear unfinished background logging tasks if we turn that flag on.

**Comment by r-peck** [comment]
No, as long as the upload is done with an NSURLSession with a background configuration, that will still work. Additionally, any upload implemented by the user of the framework would only be constrained by the environment they are using it in. If they are in an app, they could still use all those APIs. It would just limit the use of those APIs within the framework itself.

The benefit is that the framework can be used in an extension. Otherwise, any applications linking against this framework in an extension could be rejected from the App Store.

If there is intent to add direct support for uploads (not deferring to something outside the framework to implement the upload), that should probably be split out as a separate framework that extends this framework so that the core is still usable in all contexts.

**Comment by skreutzberger** [comment]
Sorry, one final question: does that just limit API access for extensions or also for users with a "normal" iOS app?

**Comment by r-peck** [comment]
The users of the framework would only be limited in extensions, which they would be whether or not this flag is set on the framework. This only limits access to those APIs from within the framework itself.

**Comment by skreutzberger** [comment]
Thanks for the explanation, now I fully understand and can appreciate the PR :+1:

**Pull request merged**
