### PR TITLE
Add support for watchOS2

### PR DESCRIPTION
**Pull request by davidrothera**
* Add support for watchOS2 extensions

# Testing

* Created new project with a watchOS app
* Added file to Podfile (example below)
* Tested
* Profit :dollar: :moneybag: 

# Example Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Test' do

end

target 'Test WatchKit App' do

end

target 'Test WatchKit Extension' do
        platform :watchos, '2.0'
        pod 'SwiftyBeaver', :path => '../SwiftyBeaver'
end
```

### CODE REVIEW

**Comment by skreutzberger** [comment]
I will also add tvOS. Just created some local test projects to try things out. just WatchOS is weird somehow but maybe I should read more tutorials how to write a quick watchOS app :D

**Comment by davidrothera** [comment]
I am still working out how to get watchOS to play nicely with Carthage and should have another PR up soon.

**Comment by skreutzberger** [comment]
I added tvOS and MacOS to the podfile. The lint'er seems to like it.

```Swift
  s.ios.deployment_target = "8.0"
  s.watchos.deployment_target = "2.0"
  s.tvos.deployment_target = "9.0"
  s.osx.deployment_target = "10.9"
````
Makes sense, doesn't it?

**Comment by davidrothera** [comment]
:+1: Seems good to me

**Comment by skreutzberger** [comment]
thanks, I will push and tag.

**Pull request merged**
