### PR TITLE
Add support for tvOS, OSX, watchOS for Carthage

### PR DESCRIPTION
**Pull request by davidrothera**
As per the title, this adds support for frameworks for:

* tvOS
* WatchOS
* OSX
* iOS

### CODE REVIEW

**Comment by davidrothera** [comment]
## Changes

For some more details about what was done here:
* Remove the target device family build settings
* Duplicate targets for each of the new target device types and rename the current one to iOS

## Testing

```
[drothera@drothera-mbp Test]$ (master) carthage update
*** Fetching SwiftyBeaver
*** Checking out SwiftyBeaver at "1e906352aa688bd2dc73e55e980b48aa85513945"
*** xcodebuild output can be found in /var/folders/6s/xv5hxnvs3glb4wpqpd8r19phv7qcp3/T/carthage-xcodebuild.3iejuf.log
*** Building scheme "SwiftyBeaver (tvOS)" in SwiftyBeaver.xcodeproj
*** Building scheme "SwiftyBeaver (watchOS)" in SwiftyBeaver.xcodeproj
*** Building scheme "SwiftyBeaver (iOS)" in SwiftyBeaver.xcodeproj
*** Building scheme "SwiftyBeaver (OSX)" in SwiftyBeaver.xcodeproj
```

**Comment by davidrothera** [comment]
Fixes #17 as well

**Comment by skreutzberger** [comment]
Great! I am pulling and testing.

**Comment by skreutzberger** [comment]
I try to get it to work with Carthage build but I needed to enable Bitcode for tvOS and watchOS. Hope that is not an issue? But maybe my Xcode project needed these changes.

**Comment by davidrothera** [comment]
tvOS and WatchOS both require BitCode and there is no way around that so all good :smile:

**Comment by skreutzberger** [comment]
building for all platforms works now in Xcode but there seems an issue with Carthage :( - it may be my Xcode settings but here is the first part of the error message:
screenshot-carthage

And here is the log file: https://gist.github.com/skreutzberger/6c8089760835c623b290

**Comment by skreutzberger** [comment]
Maybe if it helps, here is my updated version of your pull request to make it work for me locally:

https://github.com/skreutzberger/SwiftyBeaver/tree/carthage_fwks

**Comment by davidrothera** [comment]
Ah I was building just with build and not no-skip-current

If it build then :shipit:

**Comment by skreutzberger** [comment]
so all is good and I should not build with no-skip-current?

**Comment by davidrothera** [comment]
It could also have been because I was building it in a fresh project. If it's building then it should be fine.

**Comment by skreutzberger** [comment]
Shall we risk a deployment to Master? I just can verify Mac OS X and iOS. I can add a new tag v0.2.5 and when things break then I can remove the tag again. Alright? What time (UTC) would work for you for that deploy-Carthage-support-to-master test?

**Comment by skreutzberger** [comment]
I pushed it to master and added tag v0.2.5

**Comment by skreutzberger** [comment]
once you give me a Go then I will push the tag to Cocoapods, too. It does not have an impact there but just to have everything in sync :)

**Comment by davidrothera** [comment]
Works a treat for me :+1:

**Comment by skreutzberger** [comment]
Happily merged. closed by ac3b2571

**Pull request closed without merging**
