### PR TITLE
Add support for Swift package manager

### PR DESCRIPTION
**Pull request by davidrothera**
* Move the Swift sources to `sources/` which is required :truck: 
  * Changed the xcodeproj to support these new locations
  * Changed the location of the sources in the podspec
* Amend the README showing how to use it as a package :memo: 
* Create a package definition :8ball: 

Once this is pushed a new tag/version needs to be pushed for it to work as a Swift Package. :rocket: 

This diff also fixes some whitespace in the README file

### CODE REVIEW

**Comment by davidrothera** [comment]
Fixes #19

**Comment by davidrothera** [comment]
```
[drothera@drothera-mbp SwiftyBeaver]$ (swiftpm) pod lib lint

 -> SwiftyBeaver (0.2.2)

SwiftyBeaver passed validation.
```

**Comment by skreutzberger** [comment]
Wow, that is fantastic! I pulled it and after some file reference mangling with my local project it builds and all unit tests work. I'll just grab a pizza now and then do the merge, build, release dance :pizza: :dancers: 

Do you have an option to test it once on master? And does it require a new tag?

**Comment by davidrothera** [comment]
It requires a new tag as the Swift PM downloads the latest tag and looks for the `Package.swift`.

I tested on a branch of my own with new tags etc and it works a treat.

Once you have merged I will test and confirm it still all works :+1:

**Comment by davidrothera** [comment]
Checked and everything works under master with no issues :+1: 

```
[drothera@drothera-mbp sbtest]$ ./.build/debug/SBTest
[2015-12-09 13:54:02.485] main.SBTest:13 DEBUG: something to debug
[2015-12-09 13:54:02.492] main.SBTest:14 INFO: a nice information
[2015-12-09 13:54:02.492] main.SBTest:15 WARNING: oh no, that won’t be good
[2015-12-09 13:54:02.492] main.SBTest:16 ERROR: ouch, an error did occur!
[2015-12-09 13:54:02.493] main.SBTest:19 VERBOSE: 123
[2015-12-09 13:54:02.493] main.SBTest:20 INFO: -123.45678
[2015-12-09 13:54:02.493] main.SBTest:21 WARNING: 2015-12-09 13:54:02 +0000
[2015-12-09 13:54:02.493] main.SBTest:22 ERROR: ["I", "like", "logs!"]
[2015-12-09 13:54:02.493] main.SBTest:23 ERROR: ["address": "7 Beaver Lodge", "name": "Mr Beaver"]
hello world
```

**Comment by skreutzberger** [comment]
OMG, how cool is that?! Thank you :+1:   - I need to also dive into the Swift Package Manager, it really seems more than awesome!

**Comment by davidrothera** [comment]
At the moment it is very limited as there is no support for iOS/OSX etc but once there is better support yeah it should be awesome

**Pull request merged**
