### PR TITLE
add tvOS support and make date string optional

### PR DESCRIPTION
**Pull request by yonaskolb**

### CODE REVIEW

**Comment by skreutzberger** [comment]
Hi, thanks for the PR. About the tvOS: did you test it? I just read that SwiftyBeaver does not yet work under tvOS because it is not built for it or is that just an issue of Carthage but I am not a Cocoapods expert ...

Also please always create for every bugfix, addition and feature request a new pull request. That makes it easier to discuss and to merge. Thanks!

**Comment by davidrothera** [comment]
Another note, I would not change the date to be false by default as that goes against current defaults.

**Comment by yonaskolb** [comment]
It seems to build and run fine on the Apple TV with this change.
Sorry for the incorrect addition of the date string commit. This was originally supposed to be just a tvOS pull request, but I accidentally created it from master and pushed another commit to that (including an incorrect default of false!)

**Comment by davidrothera** [comment]
Cool, can you rebase and just pick the tvOS change :+1:

**Comment by skreutzberger** [comment]
@yonaskolb I took your no-date feature request and refactored the existing codebase to make the additionally property unnecessary. Commit: 682b7a0f15

To get rid of the date the user just needs to leave the date format empty. I will add that to the docs. 

About tvOS: it is great that it is really just a tiny change in cocoapods. Can we also get WatchOS support by adding another line? 

I am closing this pull request to stay organized.

**Comment by davidrothera** [comment]
In theory yes, as this library just uses Foundation and watchOS has that.

The rule in the podspec just tells cocoapods to generate a framework that has watchOS support enabled.

**Comment by skreutzberger** [comment]
Can you tell me the lines or do a PR? I really should take some time to create a small build farm to test for all these devices.

**Comment by davidrothera** [comment]
I'll get a PR up shortly

**Pull request closed without merging**
